# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiCwRRVLr-bXtD5TrsqawczqEpsF7ChZ
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()

df.tail(
)

clean_df = df.dropna()

clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max(

)

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df['Undergraduate Major'][43]

clean_df.loc[43]

clean_df['Mid-Career Median Salary'].max()

clean_df['Mid-Career Median Salary'].idxmax()

clean_df.loc[8]

clean_df['Starting Median Salary'].idxmin()

clean_df.loc[49]

clean_df['Mid-Career Median Salary'].idxmin()

clean_df.loc[18]

lowest_salary_difference = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

lowest_salary_difference.idxmin()

clean_df.loc[40]

clean_df.insert(1, "Spread", lowest_salary_difference)

clean_df.head()

low_risk = clean_df.sort_values('Spread')

low_risk[["Undergraduate Major", "Spread"]].head()

low_risk[["Undergraduate Major", "Spread"]].tail()

highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

clean_df.groupby('Group').count()

numeric_columns = ['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 90th Percentile Salary', 'Spread']
clean_df.groupby('Group')[numeric_columns].mean()

pd.options.display.float_format = '{:,.2f}'.format

numeric_columns = ['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 90th Percentile Salary', 'Spread']
clean_df.groupby('Group')[numeric_columns].mean()

